apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    {{- include "devops-web-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "devops-web-platform.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: {{ .Values.services.backendPort }}
      targetPort: http
      protocol: TCP
