apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devops-web-platform.fullname" . }}-config
  labels:
    {{- include "devops-web-platform.labels" . | nindent 4 }}
data:
  DB_HOST: "{{ include "devops-web-platform.fullname" . }}-mysql"
  APP_VERSION: {{ .Values.images.backend.tag | quote }}
  DB_PORT: "{{ .Values.services.mysqlPort }}"
  DB_NAME: "{{ .Values.mysql.database }}"
