apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: devops-platform
servers: 1
agents: 0
image: rancher/k3s:v1.36.1-k3s1
ports:
  - port: 127.0.0.1:8080:80
    nodeFilters:
      - loadbalancer
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
